config/routes.rb
Rails.application.routes.draw do
  root 'home#top'

  delete '/logout' => 'session#destroy'

  get '/about' => 'home#about'
  get '/works/index'=> 'works#index'
  post '/works/create' => 'works#create'
  get '/works/new' => 'works#new'
  get '/works/:id'=> 'works#show'
  get '/works/:id/edit' => 'works#edit'
  post '/works/:id/update' => 'works#update'
  post '/works/:id/destroy' => 'works#destroy'
  get '/sign_up' => 'users#new'
  post '/sign_up' => 'users#create'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/users/:id' => 'users#show'


  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence:true, length:{minimum:4, maximum:16},
              uniqueness:true

  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, length:{maximum:255},
              format:{with:VALID_EMAIL_REGEX},
              uniqueness:true

  has_secure_password
  validates :password, presence:true, length:{minimum:6, maximum:16},
              uniqueness:true
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user=User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to(user)
    else
      flash.now[:danger]="Invailid email/password combination"
      render"new"
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success]="welcome to the RoutineMaker!"
      redirect_to @user
    else
     render 'new'
   end
  end

  def destroy
    redirect_to (root_path)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @work=Work.all
  end

  def new
  end

  def create
    @work=Work.new(title: params[:title], detail: params[:detail])
    @work.save
    redirect_to("/works/index")
  end

  def show
    @work=Work.find_by(id: params[:id])
  end

  def edit
    @work=Work.find_by(id: params[:id])
  end

  def update
    @work=Work.find_by(id: params[:id])
    @work.title=params[:title]
    @work.detail=params[:detail]
    @work.save
    redirect_to("/works/index")
  end

  def destroy
    @work=Work.find_by(id: params[:id])
    @work.destroy
    redirect_to("/works/index")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(user)
    session[:user_id]=user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    p "============================"
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper

    # 引数で与えられたユーザーのGravatar画像を返す
    def gravatar_for(user)
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/home/about.html.erb
<div class="main about-main">
  <h1>良い習慣で、良き日々を</h1>
  <h2>
    ・資格のための勉強を始めたい</br>
    ・楽器を引けるようになりたい</br>
    ・健康のために運動したい</br>
    etc...</br>
    </br>
    より良い日々のため新しい習慣を作りたい</br>
      Routine Maker（ルーティンメイカー）</br>
    はそんな貴方をサポートします</br>
</h2>
</div>

app/views/home/top.html.erb
<div class="center jumbotron">
  <div class="top-main main">
    <h1>Routine Maker</h1>
    <h2>良い習慣で、良き日々を</h2>

    <%= link_to "Sign up now!", 'sign_up', class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <%= link_to image_tag("logo_RM_main.png", alt: "RoutineMaker"),  '/' %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "一覧", works_index_path %></li>
          <li><%= link_to "新規作成", works_new_path %></li>
          <li><%= link_to "プロフィール", current_user%></li>
          <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ホーム",   '/' %></li>
          <li><%= link_to "ルーティンメイカーとは", about_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <%end%>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoutineMaker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= render "layouts/shim" %>
  <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <%flash.each do |message_type, message| %>
          <div class="alert alert-<%=message_type %>"><%=message %></div>
        <%end%>
      <%= yield %>
      <%= debug(params)if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/session/new.html.erb
<%provide(:title, "Log in")%>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%=f.label :email %>
      <%=f.text_field :email, class:"form-controll"%>

      <%=f.label :password%>
      <%=f.password_field :password, class:"form-controll"%>

      <%=f.submit"Log in", class:"btn btn-primary"%>
      <%end%>

      <p>New user? <%=link_to "Sign up now!", "sign_up" %></p>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
  <%end%>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", 'sign_up', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>

<div class="row">
  <div>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

     <%= f.label :name %>
     <%= f.text_field :name, class:'form-control'%>

     <%= f.label :email %>
     <%= f.email_field :email, class:'form-control' %>

     <%= f.label :password %>
     <%= f.password_field :password, class:'form-control' %>

     <%= f.label :password_confirmation, "Confirmation" %>
     <%= f.password_field :password_confirmation , class:'form-control'%>

     <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name)%>
<div class="row">
  <div class="col-sm-2 col-md-2">

            <%= gravatar_for @user %>

  </div>
  <div class="col-sm-10 col-md-10">
    <div class="aside">
      <section>
        <h3>name:<%= @user.name %><br/></h3>
        email:<%= @user.email %>
      </section>
    </div>
  </div>
</div>
<div class="row jumbotron">
  <h2>ここにWorkが入る</h2>

  <div class="row">
    <div class="col-sm-4 col-md-4"></div>

    <div class="col-sm-4 col-md-4"></div>
</div>

app/views/works/edit.html.erb
<div class="container">
  <%= form_tag("/works/#{@work.id}/update") do%>
    <div class="form">
      <div class="form-body">
        <textarea name="title"><%= @work.title %></textarea>
        <textarea name="detail"><%= @work.detail %></textarea>
        <input type="submit" value="保存" class="btn btn-lg btn-primary">
      </div>
    <% end %>
  </div>
</div>

app/views/works/index.html.erb
<div class="container">

<h1>目標一覧</h1>
<h2>習慣化に取組中</h2>

  <% @work.each do |work| %>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="work-main col-md-8">
        <div class="work-index-title">
          <%= link_to(work.title,"/works/#{work.id}") %>
        </div>
        <div class="work-index-item">
          <%= work.detail %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/works/new.html.erb
<div class="work-main">
      <h1>新規目標作成</h1>
    <%= form_tag("/works/create") do%>
      <p>タイトル：</p>
      <textarea name="title"></textarea>
      <p>内容：</p>
      <textarea name="detail"></textarea>
      <input class="btn btn-lg btn-primary"　type="submit" value="投稿" >
    <% end %>
  </div>

app/views/works/show.html.erb
<h2>
  <%= @work.title %>
</h2>
<p>
  <%= @work.detail %>
</p>
<p>
  <%= link_to("編集","/works/#{@work.id}/edit")%>
  <%= link_to("削除","/works/#{@work.id}/destroy",{method:"post"})%>
</p>